global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pollen-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pollen-app:8080']  # Utilisez le nom du service et le port correct